apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.0.8
    helm.sh/chart: fluent-bit-0.22.0
data:
  stream_processor.conf: |
    [STREAM_TASK]
       Name   otel_logs
       Exec   CREATE STREAM otel_logs_count WITH (tag='otel.count') AS SELECT kubernetes_pod_name,COUNT(*) from TAG:'modify.*' WINDOW TUMBLING (5 SECOND)  WHERE kubernetes_namespace_name='otel-demo' GROUP BY kubernetes_pod_name ;

  custom_parsers.conf: |
    [PARSER]
       Name docker_no_time
       Format json
       Time_Keep Off
       Time_Key time
       Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
       Daemon Off
       Flush 1
       Log_Level info
       Parsers_File   parsers.conf
       Parsers_File custom_parsers.conf
       HTTP_Server On
       HTTP_Listen 0.0.0.0
       HTTP_Port 2020
       Health_Check On
       Streams_File stream_processor.conf
    [INPUT]
       Name tail
       Path  /var/log/containers/*.log
       multiline.parser docker, cri
       Tag kube.*
       Mem_Buf_Limit 5MB
       Skip_Long_Lines On

    [INPUT]
       name fluentbit_metrics
       tag  otel.fluent
       scrape_interval 2

    [INPUT]
       name node_exporter_metrics
       tag  otel.node
       scrape_interval 2

    [INPUT]
       name prometheus_scrape
       host prometheus-kube-state-metrics.default.svc
       port 8080
       tag otel.metrics
       metrics_path /metrics
       scrape_interval 10s

    [FILTER]
       Name kubernetes
       Match kube.*
       Merge_Log On
       Keep_Log Off
       K8S-Logging.Parser    On
       K8S-Logging.Exclude On
    [FILTER]
       Name nest
       Match kube.*
       Operation lift
       Nested_under kubernetes
       Add_prefix   kubernetes_
    [FILTER]
       Name grep
       Match kube.*
       Exclude kubernetes_container_name fluent-bit
    [FILTER]
       Name nest
       Match kube.*
       Operation lift
       Nested_under kubernetes_labels
    [FILTER]
       Name          rewrite_tag
       Match         kube.*
       Rule          $kubernetes_namespace_name ^(([a-z0-9A-Z]+)-*([a-z0-9A-Z]*))$ modify.$kubernetes_namespace_name true
       Emitter_Name  re_emitted
    [FILTER]
       Name modify
       Match kube.*
       Rename log content
       Rename kubernetes_pod_name k8s.pod.name
       Rename kubernetes_namespace_name k8s.namespace.name
       Remove kubernetes_container_image
       Remove kubernetes_docker_id
       Remove kubernetes_container_name
       Remove kubernetes_pod_id
       Remove kubernetes_host
       Remove kubernetes_annotations
       Remove time
       Remove kubernetes_container_hash
       Add k8s.cluster.name CLUSTER_NAME_TO_REPLACE
       Add dt.kubernetes.config.id CLUSTER_ID_TOREPLACE

    [FILTER]
       Name     throttle
       Match    *
       Rate     800
       Window   3
       Print_Status  true
       Interval 30s

    [OUTPUT]
       Name http
       Match kube.*
       host  DT_URL_TO_REPLACE
       port 443
       URI /api/v2/logs/ingest
       header Authorization Api-Token DT_TOKEN_TO_REPLACE
       header Content-type application/json; charset=utf-8
       Format json_stream
       allow_duplicated_headers false
       Json_date_key timestamp
       Json_date_format iso8601
       tls On
       tls.verify Off
       Retry_Limit false


    [OUTPUT]
       name            prometheus_exporter
       match           otel.*
       host            0.0.0.0
       port            2021
       # add user-defined labels
       add_label      k8s.cluster.name CLUSTER_NAME_TO_REPLACE


    [OUTPUT]
       Name stdout
       Match *

