apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: oteld
  labels:
    app: opentelemetry
spec:
  mode: daemonset
  hostNetwork: true
  image: otel/opentelemetry-collector-contrib:0.72.0
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800


      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30


    exporters:
      logging:
        verbosity: detailed

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [logging]

